### ISSUE TITLE
Thread.join causes knapsack to hang on circleCI

### ISSUE THREAD

**Issue by quynhethereal** [KnapsackPro/knapsack_pro-ruby#179]
Hi, I'm encountering a weird behavior. 

My pseudo-code looks like this: 
```ruby

Class MyTask
  def order_now
   # Some DB transactions here

   MyModel.transaction do

    Thread.new do
      ActiveRecord::Base.connection_pool.with_connection do
        # Open another DB connection update progress status while in transaction
      end.join   
  end
end
end
```

And my rspec: 

```ruby
context 'it works' do
  it 'works' do 
      service.call
      expect(service).to be_success
  end
end
```

This works on my local machine. However, `Thread.join` cause my CI running with Knapsack to hang indefinitely, only to be terminated after 10-minute by CircleCI. There was no error, but here is the log. 

>{"severity":"ERROR","thread_id":47130853734740,"process_id":362,"message":"/home/********/my-project/app/services/custom_reports/export.rb:72:in `join'\n/home/********/my-project/app/services/custom_reports/export.rb:72:in `block (3 levels) in each_rows'\n/home/********/my-project/app/services/custom_reports/export.rb:47:in `loop'\n/home/********/my-project/app/services/custom_reports/export.rb:47:in `block (2 levels) in each_rows'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'\n/home/********/my-project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.8/lib/active_record/transactions.rb:212:in `transaction'\n/home/********/my-project/app/services/custom_reports/export.rb:46:in `block in each_rows'\n/home/********/my-project/app/services/custom_reports/export.rb:17:in `each'"}

CI is using : `gem 'knapsack_pro', '~>2.11.0'`.

**Comment by ArturT** [comment]
* Shouldn't you call the `join` method on each created thread? I see you called the `join` method only on the active record object.
https://stackoverflow.com/a/3481898/905697

* Is the problem happening on CI without the knapsack_pro gen?
* What database engine do you use? Maybe DB transactions are locked (deadlock) and waiting for each other on CI?
* Can you try [the latest version of the knapsack_pro gem](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md)?

**Comment by quynhethereal** [comment]
@ArturT Thanks for the prompt reply.

For 1, I actually want the AR thread to block the main thread, and then join with the main thread after it updates, as demonstrated in: https://stackoverflow.com/a/44730822 and https://stackoverflow.com/a/11675647.
 
For 2, I only run the test in local with Rspec and they passed. My CI is using Knapsack so I suspect this has sth to do with the issue. 
 
For 3, it is Postgres 13:2. 

>Maybe DB transactions are locked (deadlock) and waiting for each other on CI?

I commented out all the Rspec tests and it still hangs. Somehow *just* having the `Thread.join` in the code will cause Knapsnack to be unable to proceed. Remove `join` out of the Thread and everything is fine again i.e: 

```Class MyTask
  def order_now
   # Some DB transactions here

   MyModel.transaction do

    Thread.new do
      ActiveRecord::Base.connection_pool.with_connection do
        # Open another DB connection update progress status while in transaction
      end # remove join here makes everything works, transaction or not  
    end
 end
end
```

For 4, sure thing, let me get back to you.

**Comment by quynhethereal** [comment]
@ArturT My bad, sorry, the join was supposed to be on the end of the Thread. It was an honest when I copy pasted. So in my (real) code, it does look like this: 

```ruby

Class MyTask
  def order_now
   # Some DB transactions here

   MyModel.transaction do

    Thread.new do
      ActiveRecord::Base.connection_pool.with_connection do
        # Open another DB connection update progress status while in transaction
      end
    end.join # <----- join should be called on the thread object in order to block the main thread.
 end
end

```

Let me make the corrections to my comments 🙏

**Comment by ArturT** [comment]
Do you use Queue Mode or Regular Mode in Knapsack Pro?
You can check if the test is hanging in both modes.

**Comment by quynhethereal** [comment]
> Do you use Queue Mode or Regular Mode in Knapsack Pro?
You can check if the test is hanging in both modes.
 
I'm using Queue Mode. I just ran the code with the latest Knapsack gem and it still hangs, so let me try the regular one. 

The behavior I got was that Knapsack logs out something likes this: 
> Knapsack Pro Queue finished!
> Finished in 10 minutes 44 seconds
> 2464 examples, 0 failures

But it is unable to exit.

Then after some time, it is killed by the CI:
> Too long with no output (exceeded 10m0s): context deadline exceeded

**Comment by ArturT** [comment]
I saw a similar problem among other users from time to time, and it was some leftovers created during RSpec runtime that caused hanging. Maybe you have a not closed connection to DB? Typically it's something like that.

You can clean up the environment with a hook:

```ruby
KnapsackPro::Hooks::Queue.after_queue do |queue_id|
  print 'After Queue Hook - run after test suite'
end
```

https://knapsackpro.com/faq/question/what-hooks-are-supported-in-queue-mode
https://knapsackpro.com/faq/question/what-is-the-order-of-rspec-hooks-in-the-queue-mode

**Comment by quynhethereal** [comment]
@ArturT Thanks for sharing the insights, I suspect this too. It is reliving to know this is an issue that has happened before. 

> I saw a similar problem among other users from time to time, and it was some leftovers created during RSpec runtime that caused hanging. Maybe you have a not closed connection to DB? Typically it's something like that.

 
Interestingly, after using Regular Mode, the time taken to run the CI reduces from 10 mins -> 3 mins :o 

The hanging no longer exists. Would this be odd to you?

**Comment by ArturT** [comment]
Can you share a link to the knapsack user dashboard with both CI builds?

**Comment by ArturT** [comment]
> I took a look at your docs for knapsack user dashboard. It seems like a feature for Heroku-based applications or enterprises with SAML login, which are not applicable to my company.

I'm a bit confused. I assume you already have an account at https://knapsackpro.com because you use Queue Mode. Every user has access to the dashboard. Whether you are on a free or paid plan, you can access the dashboard here https://knapsackpro.com/dashboard/ and check build metrics to see your latest recorded CI builds. 

If you don't want to share private company stuff here in a public GitHub issue, you can shoot me an email at support inbox https://knapsackpro.com/contact

You can also share a git commit hash, and I can find builds myself this way.

> Another update is although the Regular mode removes the hang for the Unit tests, it transfers the "unresponsive" behavior to the Acceptance test sets, so let me try and find if there indeed some Rspec leftovers that caused this. In the meantime, let me know if you have any ideas. Thank you!

Here are a few common hanging reasons:
https://knapsackpro.com/faq/question/why-knapsack_pro-freezes--hangs-my-ci-for-instance-travis
https://knapsackpro.com/faq/question/why-knapsack_pro-hangs-freezes-is-stale-for-tests-in-chrome-disallow-downloads-in-sandboxed-iframes
https://knapsackpro.com/faq/question/why-knapsack_pro-hangs--freezes--is-stale-ie-for-codeship-in-queue-mode

**Comment by ArturT** [comment]
@quynhethereal I'm glad you found the root issue. Cheers!
