### ISSUE TITLE
Infinite recursion when KNAPSACK_PRO_LOG_LEVEL is set to debug

### ISSUE THREAD

**Issue by dmytro-workday** [KnapsackPro/knapsack_pro-ruby#269]
Hi,

We have set `KNAPSACK_PRO_LOG_LEVEL=debug` and `KNAPSACK_PRO_LOG_DIR=log`, which leads to the following backtrace:

```
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] SystemStackError: stack level too deep (SystemStackError)
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:240:in `map'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:240:in `detected_ci'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:292:in `ci_env_for'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:282:in `env_for'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:20:in `ci_node_index'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro.rb:99:in `logger'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:285:in `env_for'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:20:in `ci_node_index'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro.rb:99:in `logger'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:285:in `env_for'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro/config/env.rb:20:in `ci_node_index'
[2024-08-15 12:56:16] [2024-08-15 12:56:16] [NODE=4] /builds/app/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.8.0/lib/knapsack_pro.rb:99:in `logger'
```

Seems like the issue is related to the following warnings, throws when the logging directory is not enabled:

```
You have set the environment variable KNAPSACK_PRO_CI_NODE_TOTAL to 36 which could be automatically determined from the CI environment as 9.
You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 1 which could be automatically determined from the CI environment as 0.
```

The configuration we used is similar to the FAQ answer here:

https://knapsackpro.com/faq/question/parallel_tests-with-knapsack_pro-on-parallel-ci-nodes

**Comment by ArturT** [comment]
@dmytro-workday Could you work around the issue while we look into it? Or is this preventing you from using Knapsack Pro?

**Comment by dmytro-workday** [comment]
Yes. We have removed the `_LOG_` variables for now and assigning the logger directly:

```ruby
logger = Logger.new("log/knapsack_pro_node_#{KnapsackPro::Config::Env.ci_node_index}.log")
logger.level = ::Logger::DEBUG
KnapsackPro.logger = logger
```

**Comment by karoisuzvards** [comment]
@ArturT seems that there are some issues (though not sure if related) - only following items are found in `log/knapsack_pro_node_N.log`:

```
# Logfile created on 2025-07-09 11:11:48 +0000 by logger.rb/v1.7.0
D, [2025-07-09T11:15:27.924828 #579] DEBUG -- : [knapsack_pro] Global test execution duration: 03m 38s
I, [2025-07-09T11:15:27.925020 #579]  INFO -- : [knapsack_pro] You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 20 which could be automatically determined from the CI environment as 2.
I, [2025-07-09T11:15:27.925104 #579]  INFO -- : [knapsack_pro] You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 20 which could be automatically determined from the CI environment as 2.
D, [2025-07-09T11:17:29.742483 #774] DEBUG -- : [knapsack_pro] Global test execution duration: 01m 53s
I, [2025-07-09T11:17:29.742735 #774]  INFO -- : [knapsack_pro] You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 20 which could be automatically determined from the CI environment as 2.
I, [2025-07-09T11:17:29.742852 #774]  INFO -- : [knapsack_pro] You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 20 which could be automatically determined from the CI environment as 2.
```

its only observable for **cucumber**, for **rspec** its fine - for cucumber the logger setup code in **env.rb**

```ruby
KnapsackPro::Adapters::CucumberAdapter.bind
logger = Logger.new("log/knapsack_pro_node_#{KnapsackPro::Config::Env.ci_node_index}.log")
logger.level = ::Logger::DEBUG
KnapsackPro.logger = logger
```

**Comment by ArturT** [comment]
I've managed to reproduce [the issue](https://github.com/KnapsackPro/knapsack_pro-ruby/issues/269#issue-2468011089) locally. I'll bring this up to our team. 



> [@ArturT](https://github.com/ArturT) seems that there are some issues (though not sure if related) - only following items are found in `log/knapsack_pro_node_N.log`:
> 
> ```
> # Logfile created on 2025-07-09 11:11:48 +0000 by logger.rb/v1.7.0
> D, [2025-07-09T11:15:27.924828 #579] DEBUG -- : [knapsack_pro] Global test execution duration: 03m 38s
> I, [2025-07-09T11:15:27.925020 #579]  INFO -- : [knapsack_pro] You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 20 which could be automatically determined from the CI environment as 2.
> I, [2025-07-09T11:15:27.925104 #579]  INFO -- : [knapsack_pro] You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 20 which could be automatically determined from the CI environment as 2.
> D, [2025-07-09T11:17:29.742483 #774] DEBUG -- : [knapsack_pro] Global test execution duration: 01m 53s
> I, [2025-07-09T11:17:29.742735 #774]  INFO -- : [knapsack_pro] You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 20 which could be automatically determined from the CI environment as 2.
> I, [2025-07-09T11:17:29.742852 #774]  INFO -- : [knapsack_pro] You have set the environment variable KNAPSACK_PRO_CI_NODE_INDEX to 20 which could be automatically determined from the CI environment as 2.
> ```
> 
> its only observable for **cucumber**, for **rspec** its fine - for cucumber the logger setup code in **env.rb**
> 
> KnapsackPro::Adapters::CucumberAdapter.bind
> logger = Logger.new("log/knapsack_pro_node_#{KnapsackPro::Config::Env.ci_node_index}.log")
> logger.level = ::Logger::DEBUG
> KnapsackPro.logger = logger

It's not related. Are you referring to a situation when some messages are logged in the log file and some are not (they are still in the stdout)?

This is happening because the following logger configuration snippet is loaded after some messages are already printed to stdout by the Knapsack Pro logger.

```ruby
KnapsackPro::Adapters::CucumberAdapter.bind
logger = Logger.new("log/knapsack_pro_node_#{KnapsackPro::Config::Env.ci_node_index}.log")
logger.level = ::Logger::DEBUG
KnapsackPro.logger = logger
```

There is no simple way to avoid that if you keep logger configuration in `env.rb`.

The best approach would be to set `KNAPSACK_PRO_LOG_DIR=log`, then `log/knapsack_pro_node_#{KnapsackPro::Config::Env.ci_node_index}.log` is [a default log file](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/d3d0e11aabdc406465104c319fed0aa4854e16ef/lib/knapsack_pro.rb#L100). No need to add the snippet to the `env.rb` for Cucumber.

Please try `KNAPSACK_PRO_LOG_DIR=log`. If you encounter [the issue](https://github.com/KnapsackPro/knapsack_pro-ruby/issues/269#issue-2468011089) let us know.
