### ISSUE TITLE
Ruby 2.6 not supported

### ISSUE THREAD

**Issue by trevorrjohn** [KnapsackPro/knapsack_pro-ruby#74]
Getting this error once I updated to ruby 2.6.0
```
Randomized with seed 34743
--
  | .............................................................................................................................
  | An error occurred in an `after(:suite)` hook.
  | Failure/Error:
  | def initialize(io, read_timeout: 60, continue_timeout: nil, debug_output: nil)
  | @read_timeout = read_timeout
  | @rbuf = ''.dup
  | @debug_output = debug_output
  |  
  | @io = case io
  | when Socket, OpenSSL::SSL::SSLSocket, IO
  | io
  | when StringIO
  | PatchedStringIO.new(io.string)
  |  
  | ArgumentError:
  | unknown keyword: write_timeout
  | # /usr/local/bundle/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:259:in `initialize'
  | # /usr/local/bundle/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:109:in `request'
  | # /usr/local/bundle/gems/knapsack_pro-1.2.0/lib/knapsack_pro/client/connection.rb:91:in `post'
  | # /usr/local/bundle/gems/knapsack_pro-1.2.0/lib/knapsack_pro/client/connection.rb:12:in `call'
  | # /usr/local/bundle/gems/knapsack_pro-1.2.0/lib/knapsack_pro/report.rb:59:in `create_build_subset'
  | # /usr/local/bundle/gems/knapsack_pro-1.2.0/lib/knapsack_pro/report.rb:11:in `save'
  | # /usr/local/bundle/gems/knapsack_pro-1.2.0/lib/knapsack_pro/adapters/rspec_adapter.rb:49:in `block (2 levels) in bind_save_report'
  | D, [2019-01-07T12:40:14.168012 #14] DEBUG -- : [knapsack_pro] Global time execution for tests: 42s
```

**Comment by trevorrjohn** [comment]
Sorry this might be webmock, gonna close and dig a bit

**Comment by ArturT** [comment]
@trevorrjohn Please let me know when you will find out what was the root problem and how you fixed it. Thanks!

**Comment by trevorrjohn** [comment]
This was an issue with webmock. You must update webmock `>= 3.5` to get it to work
